[package]
name = "sf-nano-cli-minimal"
version = "0.1.0"
edition = "2021"
authors = ["Bill Ming <mbbill@gmail.com>"]
description = "Minimal no_std WebAssembly runner using sf-nano-core (no WASI, no fusion)"
license = "MIT/Apache-2.0"

[[bin]]
name = "sf-nano-cli-minimal"
path = "src/main.rs"

[workspace]

[features]
default = ["jit"]
jit = ["sf-nano-core/jit"]
simd = ["sf-nano-core/simd"]

[dependencies]
sf-nano-core = { path = "../sf-nano-core", default-features = false }
tracked_alloc = { package = "sf-nano-tracked-alloc", path = "../tools/tracked-alloc" }
libc = { version = "0.2", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
overflow-checks = false
