[package]
name = "sf-nano-cli"
version = "0.1.0"
edition = "2021"
authors = ["Bill Ming <mbbill@gmail.com>"]
description = "Command-line WebAssembly runner using sf-nano-core"
license = "MIT/Apache-2.0"

[[bin]]
name = "sf-nano-cli"
path = "src/main.rs"

[features]
default = ["guard-pages"]
profile = ["sf-nano-core/profile"]
micro-jit = ["sf-nano-core/micro-jit"]
fusion = ["sf-nano-core/fusion"]
interp = ["sf-nano-core/interp"]
trace = ["sf-nano-core/trace"]
function-trace = ["sf-nano-core/function-trace"]
ir-dump = ["sf-nano-core/ir-dump"]
guard-pages = ["sf-nano-core/guard-pages"]

[dependencies]
sf-nano-core = { path = "../sf-nano-core", features = ["wasi"] }
