[package]
name = "sf-nano-cli"
version = "0.1.0"
edition = "2021"
authors = ["Bill Ming <mbbill@gmail.com>"]
description = "Command-line WebAssembly runner using sf-nano-core"
license = "MIT/Apache-2.0"

[[bin]]
name = "sf-nano-cli"
path = "src/main.rs"

[features]
default = ["jit"]
jit = ["sf-nano-core/jit"]
call-trace = ["sf-nano-core/call-trace"]
memtrace = ["sf-nano-core/memtrace", "dep:sf-nano-memtrace"]
[dependencies]
sf-nano-core = { path = "../sf-nano-core", features = ["wasi", "emulator"] }
sf-nano-memtrace = { path = "../tools/memtrace", optional = true }
