[package]
name = "sf-nano-tracked-alloc"
version.workspace = true
edition = "2021"
rust-version = "1.94"
authors = ["Bill Ming <mbbill@gmail.com>"]
description = "Internal allocation statistics and standard alloc re-exports for Silverfir-nano"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mbbill/Silverfir-nano"
include = ["src/**", "tests/**", "README.md", "LICENSE-*"]

[lib]
name = "tracked_alloc"
path = "src/lib.rs"

[features]
memprof = []
